name: Run Checks
on:
  pull_request:
    paths:
    - 'flutter/news/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Test and Static Analysis
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      - id: 'secrets'
        uses: google-github-actions/get-secretmanager-secrets@v0
        with:
          secrets: |-
            news-api-key:news-multiplatform/news-api-key

      - name: Creates local file with API key
        working-directory: ./flutter/news
        run: echo '${{ steps.secrets.outputs.news-api-key }}' > .secrets.env 

      - id: 'flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - name: Retrieve Dependencies
        working-directory: ./flutter/news
        run: flutter pub get

      - name: Build Runner
        working-directory: ./flutter/news
        run: flutter pub run build_runner build

      - name: Run the tests
        working-directory: ./flutter/news
        run: flutter test

      - name: Run the static analysis
        working-directory: ./flutter/news
        run: flutter analyze
