name: Run Checks
on:
  pull_request:
    paths:
    - 'flutter/news/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Test and Static Analysis
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      - id: 'npm'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installs Firebase
        run: npm install firebase --save

      - name: Retrieve Secrets
        working-directory: ./flutter/news
        run: fetch_secrets.sh

      - id: 'flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - name: Retrieve Dependencies
        working-directory: ./flutter/news
        run: flutter pub get

      - name: Build Runner
        working-directory: ./flutter/news
        run: flutter pub run build_runner build

      - name: Run the tests
        working-directory: ./flutter/news
        run: flutter test

      - name: Run the static analysis
        working-directory: ./flutter/news
        run: flutter analyze
