name: Run Checks - News
on:
  pull_request:
    paths:
    - 'flutter/news/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Test and Static Analysis
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      - id: 'secrets'
        uses: google-github-actions/get-secretmanager-secrets@v0
        with:
          secrets: |-
            news-api-key:projects/859887479109/secrets/NEWS_API_KEY/versions/1

      - name: Creates local file with API key
        working-directory: ./flutter/news
        run: echo "NEWS_API_KEY=${{ steps.secrets.outputs.news-api-key }}" > .secrets_env

      - id: 'flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - name: Retrieve Dependencies
        working-directory: ./flutter/news
        run: flutter pub get

      - name: Build Runner
        working-directory: ./flutter/news
        run: flutter pub run build_runner build

      - name: Run the static analysis
        working-directory: ./flutter/news
        run: flutter analyze

      - name: Run the tests
        working-directory: ./flutter/news
        run: flutter test --coverage --machine > test-results.json

      - name: Remove unrequired files from coverage
        working-directory: ./flutter/news
        run: flutter pub global activate remove_from_coverage && flutter pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./flutter/news/coverage/lcov.info
          minimum-coverage: 75
          artifact-name: news-code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./flutter/news

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          working-directory: ./flutter/news
          name: test-results
          path: test-results.json
