name: 'News Test Report'
on:
  workflow_run:
    workflows: ['Run Checks - News']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Tests Results
        path: 'test-results.json'
        reporter: flutter-json
